"""Output rendering module.

Renders a completed :class:`~src.agent.BriefingContext` to the requested
output format (markdown or DOCX). The markdown renderer prepends a YAML
front-matter metadata header and appends the configured footer before writing
the LLM-generated briefing text to disk.

DOCX rendering is deferred to Sprint 3 and raises :exc:`NotImplementedError`.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    # Avoid circular import at runtime; BriefingContext is only needed for
    # type annotations in this module.
    from src.agent import BriefingContext

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def render_markdown(ctx: BriefingContext) -> str:  # type: ignore[name-defined]
    """Render a completed briefing context to a markdown string.

    Prepends a YAML front-matter block with run metadata to make the output
    machine-readable for downstream tooling (e.g. Obsidian, static-site
    generators). Appends the configured footer from ``config.output.footer_text``.

    Args:
        ctx: Fully populated :class:`~src.agent.BriefingContext` with
            ``briefing_text`` set by the LLM generation stage.

    Returns:
        A UTF-8 markdown string ready to write to
        ``output/{vendor_id}_{meeting_date}.md``.

    Raises:
        ValueError: If ``ctx.briefing_text`` is ``None`` or empty.
    """
    if not ctx.briefing_text:
        raise ValueError(
            "render_markdown() called but ctx.briefing_text is empty. "
            "Ensure _stage_generate_briefing() ran successfully before rendering."
        )

    footer_text = (
        ctx.config.get("output", {}).get("footer_text", "Generated by Supplier Collab AI Agent")
    )
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    provider = ctx.provider.provider if ctx.provider else "unknown"
    model = ctx.provider.model if ctx.provider else "unknown"

    front_matter = (
        "---\n"
        f"vendor_id: {ctx.vendor_id}\n"
        f"meeting_date: {ctx.meeting_date}\n"
        f"persona_emphasis: {ctx.persona_emphasis}\n"
        f"generated_at: {generated_at}\n"
        f"llm_provider: {provider}\n"
        f"llm_model: {model}\n"
        f"pipeline_notes_count: {len(ctx.pipeline_notes)}\n"
        "---\n\n"
    )

    footer = f"\n\n---\n*{footer_text}*\n"

    document = front_matter + ctx.briefing_text + footer
    logger.info(
        "Rendered markdown briefing: vendor=%s, date=%s, chars=%d.",
        ctx.vendor_id, ctx.meeting_date, len(document),
    )
    return document


# ---------------------------------------------------------------------------
# DOCX renderer (Sprint 3)
# ---------------------------------------------------------------------------

def render_docx(ctx: BriefingContext, output_path: Path) -> Path:  # type: ignore[name-defined]
    """Render a completed briefing context to a ``.docx`` Word document.

    Uses the same section structure as :func:`render_markdown` with additional
    formatting: heading styles, a formatted scorecard table, a colour-coded PO
    risk table (red/yellow/green rows), and the Supplier Collab AI footer.

    Args:
        ctx: Fully populated :class:`~src.agent.BriefingContext`.
        output_path: Destination ``.docx`` file path. Parent directory must
            exist. Existing files are overwritten.

    Returns:
        The resolved ``output_path`` of the written document.

    Raises:
        NotImplementedError: Until Sprint 3 implementation.
    """
    if not ctx.briefing_text:
        raise ValueError("render_docx() called but ctx.briefing_text is empty.")

    import re
    from docx import Document
    from docx.shared import RGBColor

    doc = Document()
    
    in_table = False
    table_data = []
    
    def process_table():
        if not table_data: return
        # Remove markdown separator row if present
        if len(table_data) > 1 and all(c.replace('-', '').strip() == '' for c in table_data[1]):
            table_data.pop(1)
            
        table = doc.add_table(rows=len(table_data), cols=len(table_data[0]))
        table.style = 'Table Grid'
        
        for i, row_data in enumerate(table_data):
            row = table.rows[i]
            row_text_lower = " ".join(row_data).lower()
            
            bg_color = None
            if i > 0: # Not header row
                # Risk tier coloring
                if 'red' in row_text_lower and 'yellow' not in row_text_lower and 'green' not in row_text_lower:
                    bg_color = RGBColor(255, 230, 230)
                elif 'yellow' in row_text_lower and 'green' not in row_text_lower:
                    bg_color = RGBColor(255, 255, 200)
                elif 'green' in row_text_lower:
                    bg_color = RGBColor(230, 255, 230)
                    
            for j, cell_text in enumerate(row_data):
                if j < len(row.cells):
                    cell = row.cells[j]
                    p = cell.paragraphs[0]
                    if i == 0:
                        p.add_run(cell_text.strip()).bold = True
                    else:
                        parts = re.split(r'(\*\*.*?\*\*)', cell_text.strip())
                        for part in parts:
                            if part.startswith('**') and part.endswith('**'):
                                p.add_run(part[2:-2]).bold = True
                            else:
                                p.add_run(part)
                    
                    if bg_color:
                        from docx.oxml.shared import OxmlElement
                        from docx.oxml.ns import qn
                        shd = OxmlElement('w:shd')
                        shd.set(qn('w:val'), 'clear')
                        shd.set(qn('w:color'), 'auto')
                        shd.set(qn('w:fill'), '%02x%02x%02x' % (bg_color[0], bg_color[1], bg_color[2]))
                        cell._tc.get_or_add_tcPr().append(shd)
                        
        table_data.clear()

    for line in ctx.briefing_text.split('\n'):
        stripped = line.strip()
        
        if stripped.startswith('|'):
            in_table = True
            cols = [c.strip() for c in stripped.split('|')[1:-1]]
            if cols:
                table_data.append(cols)
            continue
            
        if in_table:
            process_table()
            in_table = False
            
        if not stripped:
            continue
            
        if stripped.startswith('---'):
            continue
            
        if stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        else:
            p = doc.add_paragraph()
            parts = re.split(r'(\*\*.*?\*\*)', stripped)
            for part in parts:
                if part.startswith('**') and part.endswith('**'):
                    p.add_run(part[2:-2]).bold = True
                else:
                    p.add_run(part)

    if in_table:
        process_table()

    footer_text = ctx.config.get("output", {}).get("footer_text", "Generated by Supplier Collab AI Agent")
    p = doc.add_paragraph(f"\n{footer_text}")
    p.runs[0].italic = True
    
    doc.save(output_path)
    logger.info("Rendered DOCX briefing: vendor=%s, date=%s", ctx.vendor_id, ctx.meeting_date)
    return output_path


# ---------------------------------------------------------------------------
# Output dispatcher
# ---------------------------------------------------------------------------

def write_output(
    ctx: BriefingContext,  # type: ignore[name-defined]
    output_dir: Path,
    output_format: str,
) -> dict[str, Any]:
    """Dispatch to the appropriate renderer(s) and write files to disk.

    File names follow the pattern ``{vendor_id}_{meeting_date}.{ext}``.

    Args:
        ctx: Fully populated :class:`~src.agent.BriefingContext`.
        output_dir: Directory to write output files into. Created if absent.
        output_format: One of ``'md'``, ``'docx'``, or ``'both'``.

    Returns:
        Dict with ``'md_path'`` and/or ``'docx_path'`` keys for each written file.

    Raises:
        ValueError: If ``output_format`` is not a recognised value.
        NotImplementedError: When ``output_format`` requests DOCX (Sprint 3).
    """
    if output_format not in {"md", "docx", "both"}:
        raise ValueError(
            f"Unknown output_format '{output_format}'. "
            "Expected one of: 'md', 'docx', 'both'."
        )

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    safe_vendor = ctx.vendor_id.replace(" ", "_").replace("/", "-")
    safe_date = ctx.meeting_date.replace(":", "-")
    stem = f"{safe_vendor}_{safe_date}"

    result: dict[str, Any] = {}

    if output_format in {"md", "both"}:
        md_path = output_dir / f"{stem}.md"
        md_content = render_markdown(ctx)
        md_path.write_text(md_content, encoding="utf-8")
        result["md_path"] = md_path
        logger.info("Markdown briefing written to: %s", md_path)

    if output_format in {"docx", "both"}:
        docx_path = output_dir / f"{stem}.docx"
        render_docx(ctx, docx_path)
        result["docx_path"] = docx_path

    return result
